rainforest/config/routes.rb
Rails.application.routes.draw do

  root 'products#index'

  resources :products do 
    resources :reviews, only: [:new, :create, :destroy]
  end

  resources :users, :only => [:new, :create] #this can probably be formated like below
  resources :sessions, only: [:new, :create, :destroy]

end

rainforest/app/models/product.rb
class Product < ActiveRecord::Base
	validates :description, :name, presence: true
	validates :price_in_cents, numericality: {only_integer: true}

	def formatted_price
		price_in_dollars = price_in_cents.to_f / 100
		sprintf("%.2f", price_in_dollars)
	end

	has_many :reviews
	has_many :users, through: :reviews
end

rainforest/app/models/review.rb
class Review < ActiveRecord::Base

	belongs_to :user
	belongs_to :product
end

rainforest/app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reviews
	has_many :products, through: :reviews

	validates :name, :email, presence: true
	
end

rainforest/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def ensure_logged_in
  	unless current_user
  		flash[:alert] = "Please log in"
  		redirect_to new_session_path
  	end
  end



  private

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user
  
end

rainforest/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
  	@products = Product.all
  end

  def show
  	@product = Product.find(params[:id])

    if current_user
      @review = @product.reviews.build
    end
  end

  def new
  	@product = Product.new
  end

  def edit
  	@product = Product.find(params[:id])
  end

  def create
  	@product = Product.new(product_params)

  	if @product.save
  		redirect_to products_url
  	else
  		render :new
  	end
  end

  def update
  	@product = Product.find(params[:id])

  	if @product.update_attributes(product_params)
  		redirect_to product_path(@product)
  	else
  		render :edit
  	end		
  end

  def destroy
  	@product = Product.find(params[:id])
  	@product.destroy
  	redirect_to product_path
  end

  private
  def product_params
  	params.require(:product).permit(:name, :url, :description, :price_in_cents)
  end
  	
end

rainforest/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	before_filter :ensure_logged_in, only: [:create, :destroy]
	before_filter :load_product

  def show
  	@review = Review.find(params[:id])
  end

  def create
  	@review = @product.reviews.build(review_params)
  	@review.user = current_user

  	if @review.save
  		redirect_to products_path, notice: 'Review created successfully'
  	else
  		render 'products/show'
  	end
  end

  def destroy
  	@review = Review.find(params[:id])
  	@review.destroy
  end

  private
  def review_params
  	params.require(:review).permit(:comment, :product_id)
  end

  def load_product
  	@product = Product.find(params[:product_id])
  end

end

rainforest/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
  	if user && user.authenticate(params[:password])
  		session[:user_id] = user.id
  		redirect_to products_url, :notice => "Logged in!"
  	else
  		flash.now[:alert] = "Invalid email or passowrd"
  		render "new"
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to products_url, notice: "logged out"
  end
end

rainforest/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)

  	if @user.save
  		redirect_to products_url, notice: "Signed up!"
  	else
  		render "new"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:email, :password, :password_confirmation, :name)
  end

end

rainforest/app/helpers/application_helper.rb
module ApplicationHelper
end

rainforest/app/helpers/products_helper.rb
module ProductsHelper
end

rainforest/app/helpers/reviews_helper.rb
module ReviewsHelper
end

rainforest/app/helpers/sessions_helper.rb
module SessionsHelper
end

rainforest/app/helpers/users_helper.rb
module UsersHelper
end

rainforest/app/views/layouts/application.html.erb
<!DOCTYPE html>
<%= stylesheet_link_tag 'styles.css' %>
<html>
<head>
  <title>Rainforest</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p> 
  <% end %>

  <div class="top_bar"></div>

<%= yield %>

<div class="underline"></div>

    <p class="userinfo">
     	<% if current_user %>
    		Signed in as <%= current_user.name %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
     	<% else %>
    		<strong><%= link_to "Log in", new_session_path %></strong> or <strong><%= link_to "Sign up", new_user_path %></strong>
    	<% end %>
    </p>
</body>
</html>

rainforest/app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
	<% if @product.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

			<ul>
			<% @product.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>
	<div class="field">
		<%= f.label :url %><br />
		<%= f.text_field :url %>
	</div>
	<div class="field">
		<%= f.label :description %><br />
		<%= f.text_area :description %> 
	</div>
	<div class="field">
		<%= f.label :price_in_cents %><br />
		<%= f.number_field :price_in_cents %>
	</div>
	<div class='actions'>
		<%= f.submit %>
	</div>
<% end %>

rainforest/app/views/products/edit.html.erb
<h1>Edit Product</h1>

<div class="underline"></div>

<%= render 'form' %>

<h3><%= link_to 'Back', products_path %></h3>

rainforest/app/views/products/index.html.erb
<h1>Rainforest Products</h1>

<div class="underline"></div>

<h2><%= link_to "Add a new product", "/products/new" %></h2>
<% @products.each do |product| %>

	<div><%= image_tag product.url %></div>
	<h3> <%= link_to product.name, "/products/#{product.id}" %></h3>
	<p><%= product.description %> - $ <%= product.formatted_price %></p>
<% end %>

rainforest/app/views/products/new.html.erb
<h1>New product</h1>

<div class="underline"></div>

<%= render 'form' %>

<h2><%= link_to 'Back', products_path %></h2>

rainforest/app/views/products/show.html.erb
<h1>Products</h1>

<div class="underline"></div>

<h2><%= link_to "Back to Products", products_url %> | <%= link_to "Edit", edit_product_path(@product) %></h2>
<br /><br />
<h3><%= @product.name %></h3><br /> <p><%= @product.description %>, <%= @product.price_in_cents %></p>
<p><%= @product.formatted_price %></p>
<%= image_tag @product.url %>

<% if current_user %>
	<h3>Reviews</h3>

	<p>Reviews for <%= @product.name %></p> 

	<% @product.reviews.each do |review| %>
		<p>
			<%= review.comment %>
			<br>
			<% if review.user != nil %>
				<em> by <strong><%= review.user.name %></strong></em> 
				Added on: <%= review.created_at %>
			<% end %>
		</p> 
	<% end %>


	<h3>New Review</h3> 
	
	<%= form_for([@product, @review]) do |f| %>
		<% if @review.errors.any? %>
			<div id="error_explanation">
				<h2><%= pluralize(@review.errirs.count, "error") %> prohibited this review from being saved: </h2> 

				<ul>
				<% @review.errors.full_messages.each do |msg| %>
					<li><%= msg %></li> 
				<% end %>
				</ul>
			</div>
		<% end %> 

		<div class"field">
			<%= f.label :comment %><br />
			<%= f.text_area :comment %>
		</div>
		<div>
			<%= f.submit %>
		</div>
		<% end %>
	
	<% else %>
		<p>Please <%= link_to "log in", new_session_path %> to add or see reviews.</p>
<% end %>

rainforest/app/views/reviews/create.html.erb
<h1>Reviews#create</h1>
<p>Find me in app/views/reviews/create.html.erb</p>

rainforest/app/views/reviews/destroy.html.erb
<h1>Reviews#destroy</h1>
<p>Find me in app/views/reviews/destroy.html.erb</p>

rainforest/app/views/reviews/show.html.erb
<h1>Reviews#show</h1>
<p>Find me in app/views/reviews/show.html.erb</p>

rainforest/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

rainforest/app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="underline"></div>

<%= form_for @user do |f| %>
	<% if @user.errors.any? %>
		<div class="error_messages">
		<h2>Form is invalid</h2>
		<ul>
			<% for messages in @user.errors.full_messages %>
				<li><%= messages %></li>
			<% end %>
		</ul>
		</div>
	<% end %>
	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %><br />
	</div>
	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %><br />
	</div>
	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %><br />
	</div>
	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %><br />
	</div>
	<div class="actions"><%= f.submit %></div>
<% end %>